### ISSUE TITLE
[BUG] error after fresh install

### ISSUE THREAD

**Issue by sh1va73** [BC-SECURITY/Empire#136]
**Empire Version**
- Empire 3.1.2

**OS Information (Linux flavor, Python version)**
- OS: Kali 2020.2
- Python: 3

**Describe the bug**
I did a fresh install on Kali 200 and get this error when i start ./empire

**To Reproduce**
1. Go to '/opt/empire'
2. Click on ' ./empire'
3. Scroll down to 'error'

**Expected behavior**
error message:

./empire
[*] Loading stagers from: /opt/Empire//lib/stagers/
Traceback (most recent call last):
  File "./empire", line 1502, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 113, in __init__
    self.stagers = stagers.Stagers(self, args=args)
  File "/opt/Empire/lib/common/stagers.py", line 51, in __init__
    self.load_stagers()
  File "/opt/Empire/lib/common/stagers.py", line 76, in load_stagers
    self.stagers[stagerName] = imp.load_source(stagerName, filePath).Stager(self.mainMenu, [])
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/Empire//lib/stagers/windows/backdoorLnkMacro.py", line 7, in <module>
    from xlutils.copy import copy
  File "/usr/local/lib/python3.7/dist-packages/xlutils/copy.py", line 7, in <module>
    from xlutils.filter import process,XLRDReader,XLWTWriter
  File "/usr/local/lib/python3.7/dist-packages/xlutils/filter.py", line 10, in <module>
    import xlrd,xlwt
  File "/usr/local/lib/python3.7/dist-packages/xlwt/__init__.py", line 5, in <module>
    from .Row import Row
  File "/usr/local/lib/python3.7/dist-packages/xlwt/Row.py", line 9, in <module>
    from . import ExcelFormula
  File "/usr/local/lib/python3.7/dist-packages/xlwt/ExcelFormula.py", line 8, in <module>
    from . import ExcelFormulaParser, ExcelFormulaLexer
  File "/usr/local/lib/python3.7/dist-packages/xlwt/ExcelFormulaLexer.py", line 55, in <module>
    VERBOSE+LOCALE+IGNORECASE)
  File "/usr/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 934, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "/usr/lib/python3.7/sre_parse.py", line 901, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern

**Screenshots**

**Additional context**

**Comment by sh1va73** [comment]
I fixed it by copying an old installation from another computer. Now I have Empire working again. But I still don't know where that error came from.

**Comment by sh1va73** [comment]
Its still not working. Empire starts but I have no listeners. When  I do uselistener <tab><tab> its empty. When i  do uselistener http:
(Empire: listeners) > uselistener http
[!] Error: invalid listener module

**Comment by Hubbl3** [comment]
@sh1va73 did you run reset? Also are you ensuring that you are running as sudo? The new kali versions do not run as sudo by default anymore

**Comment by sh1va73** [comment]
Yes I am root, I just reverted and did the install again:
apt install powershell-empire
then:
sudo powershell-empire
then I get the error from my first post: 
ValueError: cannot use LOCALE flag with a str pattern

**Comment by Hubbl3** [comment]
O. Have you run `apt get update` first? You also have to remove empire completely and reinstall it when using `apt`. We don't have any control over the apt database as that is maintained by Kali so you would have to open an issue with them to get that problem addressed

**Comment by sh1va73** [comment]
I removed everything and did git clone now. I found out there is an issue with osrframework. When I install osrframework then empire breaks down. Always i get error 

[*] Loading stagers from: /opt/Empire//lib/stagers/
Traceback (most recent call last):
File "./empire", line 1502, in
main = empire.MainMenu(args=args)
File "/opt/Empire/lib/common/empire.py", line 113, in init
self.stagers = stagers.Stagers(self, args=args)
File "/opt/Empire/lib/common/stagers.py", line 51, in init
self.load_stagers()
File "/opt/Empire/lib/common/stagers.py", line 76, in load_stagers
self.stagers[stagerName] = imp.load_source(stagerName, filePath).Stager(self.mainMenu, [])
File "/usr/lib/python3.7/imp.py", line 171, in load_source
module = _load(spec)
File "", line 696, in _load
File "", line 677, in _load_unlocked
File "", line 728, in exec_module
File "", line 219, in _call_with_frames_removed
File "/opt/Empire//lib/stagers/windows/backdoorLnkMacro.py", line 7, in
from xlutils.copy import copy
File "/usr/local/lib/python3.7/dist-packages/xlutils/copy.py", line 7, in
from xlutils.filter import process,XLRDReader,XLWTWriter
File "/usr/local/lib/python3.7/dist-packages/xlutils/filter.py", line 10, in
import xlrd,xlwt
File "/usr/local/lib/python3.7/dist-packages/xlwt/init.py", line 5, in
from .Row import Row
File "/usr/local/lib/python3.7/dist-packages/xlwt/Row.py", line 9, in
from . import ExcelFormula
File "/usr/local/lib/python3.7/dist-packages/xlwt/ExcelFormula.py", line 8, in
from . import ExcelFormulaParser, ExcelFormulaLexer
File "/usr/local/lib/python3.7/dist-packages/xlwt/ExcelFormulaLexer.py", line 55, in
VERBOSE+LOCALE+IGNORECASE)
File "/usr/lib/python3.7/re.py", line 234, in compile
return _compile(pattern, flags)
File "/usr/lib/python3.7/re.py", line 286, in _compile
p = sre_compile.compile(pattern, flags)
File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
p = sre_parse.parse(p, flags)
File "/usr/lib/python3.7/sre_parse.py", line 934, in parse
p.pattern.flags = fix_flags(str, p.pattern.flags)
File "/usr/lib/python3.7/sre_parse.py", line 901, in fix_flags
raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern

**Comment by Cx01N** [comment]
Closing due to the issue being resolved.
