### ISSUE TITLE
[BUG] if UserAgent or SlackToken is set in http listener, the functionality breaks

### ISSUE THREAD

**Issue by Gl3bGl4z** [BC-SECURITY/Empire#183]
**Empire Version**
- Empire 3.1.4-0 and 3.1.5

**OS Information (Linux flavor, Python version)**
- OS: Kali linux, debian 8
- Python: 3

Package: powershell-empire
Version: 3.1.4-0kali2
Priority: optional
Section: misc
Maintainer: Kali Developers <devel@kali.org>
Installed-Size: 23.4 MB
Depends: python3-bcrypt, python3-crypto, python3-cryptography, python3-dropbox, python3-flask, python3-iptools, python3-jinja2, python3-m2crypto, python3-macholib, python3-netifaces, python3-openssl, python3-pefile, python3-pydispatch, python3-pyinstaller, python3-pyminifier, python3-requests, python3-setuptools, python3-simplejson, python3-urllib3, python3-xlrd, python3-xlutils, python3-zlib-wrapper, python3:any
Recommends: xar, bomutils, powershell
Homepage: https://github.com/BC-SECURITY/Empire

**Describe the bug**
Agent connects after stager is run on endpoint, but some errors are shown.
No commands and modules get you any response

[*] New agent S2RDF3LH checked in
[2020-04-21 06:16:48,137] ERROR in app: Exception on /login/process.php [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/powershell-empire//lib/listeners/http.py", line 1160, in handle_post
    dataResults = self.mainMenu.agents.handle_agent_data(stagingKey, requestData, listenerOptions, clientIP)
  File "/usr/share/powershell-empire/lib/common/agents.py", line 1558, in handle_agent_data
    dataToReturn.append((language, self.handle_agent_staging(sessionID, language, meta, additional, encData, stagingKey, listenerOptions, clientIP)))
  File "/usr/share/powershell-empire/lib/common/agents.py", line 1482, in handle_agent_staging
    helpers.slackMessage(slackToken,slackChannel,slackText)
  File "/usr/share/powershell-empire/lib/common/helpers.py", line 1016, in slackMessage
    resp = urllib.request.urlopen(req)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 522, in open
    req = meth(req)
  File "/usr/lib/python3.8/urllib/request.py", line 1250, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.

**To Reproduce**
1) Create a Listener
2) Create a stager or use "launcher powershell"
3) Run stager on any victim
4) Try to run any command or module
5) You get no answer

**Expected behavior**
no errors
commands can be run

**Screenshots**

**Additional context**

**Comment by Cx01N** [comment]
Closing this issue since its a duplicate with #181
