### ISSUE TITLE
[BUG] error after todays error

### ISSUE THREAD

**Issue by sh1va73** [BC-SECURITY/Empire#227]
Empire Version

Empire 3.2.2
OS Information (Linux flavor, Python version)
OS: Kali 2020.2
Python: 3.8.3
Describe the bug
Empire was running fine but after todays update I get this error:
[+] Listener successfully started!
[!] Error starting listener: table reporting has no column named timestamp
[*] Empire starting up...
Traceback (most recent call last):
File "./empire", line 1558, in
main = empire.MainMenu(args=args)
File "/opt/Empire/lib/common/empire.py", line 133, in init
dispatcher.send(signal, sender="empire")
File "/usr/local/lib/python3.8/dist-packages/pydispatch/dispatcher.py", line 333, in send
response = robustapply.robustApply(
File "/usr/local/lib/python3.8/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
return receiver(*arguments, **named)
File "/opt/Empire/lib/common/empire.py", line 185, in handle_event
log_event(cur, sender, event_type, json.dumps(signal_data), signal_data['timestamp'], task_id=task_id)
File "/opt/Empire/lib/common/events.py", line 66, in log_event
cur.execute(
sqlite3.OperationalError: table reporting has no column named timestamp

To Reproduce

Go to 'opt//empire'
git pull origin master
./empire
See error
Expected behavior
normally Empire opens without error

**Screenshots**

**Additional context**

**Comment by vinnybod** [comment]
rerun the setup script `sudo setup/reset.sh`, the db schema was updated
