### ISSUE TITLE
[BUG] sqlite3 timestamp error

### ISSUE THREAD

**Issue by 5l1v3r1** [BC-SECURITY/Empire#313]
**Empire Version**
- Empire 3.3.4-0kali1

**OS Information (Linux flavor, Python version)**
- OS: Kali Linux 2020.4
- Python: 3.7

**Describe the bug**

powershell-empire
[*] Loading stagers from: /usr/share/powershell-empire//lib/stagers/
[*] Loading modules from: /usr/share/powershell-empire//lib/modules/
[*] Loading listeners from: /usr/share/powershell-empire//lib/listeners/
[*] Empire starting up...
Traceback (most recent call last):
  File "./empire", line 1651, in <module>
    main = empire.MainMenu(args=args)
  File "/usr/share/powershell-empire/lib/common/empire.py", line 131, in __init__
    dispatcher.send(signal, sender="empire")
  File "/usr/local/lib/python3.7/dist-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/usr/local/lib/python3.7/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/share/powershell-empire/lib/common/empire.py", line 183, in handle_event
    log_event(cur, sender, event_type, json.dumps(signal_data), signal_data['timestamp'], task_id=task_id)
  File "/usr/share/powershell-empire/lib/common/events.py", line 73, in log_event
    task_id
sqlite3.OperationalError: table reporting has no column named timestamp

previous version didn't have such a problem.

**Comment by Cx01N** [comment]
Try to run `sudo ./empire --reset` before starting the server again. Otherwise, we are happy to help on our [discord ](https://discord.com/invite/P8PZPyf) channel.
