### ISSUE TITLE
[BUG] sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by mpgn** [BC-SECURITY/Empire#360]
## Empire Version
- Empire 3.5.1

## OS Information (Linux flavor, Python version)
- OS: kali
- Python: 3.8

## Describe the bug

```
[2020-10-17 23:03:17,553] ERROR in app: Exception on /login/process.php [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kali/Empire//lib/listeners/http.py", line 1174, in handle_get
    dispatcher.send(signal, sender="listeners/http/{}".format(listenerName))
  File "/usr/local/lib/python3.8/dist-packages/pydispatch/dispatcher.py", line 333, in send
    response = robustapply.robustApply(
  File "/usr/local/lib/python3.8/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/kali/Empire/lib/common/empire.py", line 189, in handle_event
    log_event(cur, sender, event_type, json.dumps(signal_data), signal_data['timestamp'], task_id=task_id)
  File "/home/kali/Empire/lib/common/events.py", line 66, in log_event
    cur.execute(
sqlite3.DatabaseError: another row available
[2020-10-17 23:05:12,946] ERROR in app: Exception on /news.php [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kali/Empire//lib/listeners/http.py", line 1112, in handle_get
    dataResults = self.mainMenu.agents.handle_agent_data(stagingKey, routingPacket, listenerOptions,
  File "/home/kali/Empire/lib/common/agents.py", line 1650, in handle_agent_data
    dispatcher.send(signal, sender="agents/{}".format(sessionID))
  File "/usr/local/lib/python3.8/dist-packages/pydispatch/dispatcher.py", line 333, in send
    response = robustapply.robustApply(
  File "/usr/local/lib/python3.8/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/kali/Empire/lib/common/empire.py", line 189, in handle_event
    log_event(cur, sender, event_type, json.dumps(signal_data), signal_data['timestamp'], task_id=task_id)
  File "/home/kali/Empire/lib/common/events.py", line 66, in log_event
    cur.execute(
sqlite3.OperationalError: database is locked
[2020-10-17 23:05:38,073] ERROR in app: Exception on /news.php [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kali/Empire//lib/listeners/http.py", line 1112, in handle_get
    dataResults = self.mainMenu.agents.handle_agent_data(stagingKey, routingPacket, listenerOptions,
  File "/home/kali/Empire/lib/common/agents.py", line 1650, in handle_agent_data
    dispatcher.send(signal, sender="agents/{}".format(sessionID))
  File "/usr/local/lib/python3.8/dist-packages/pydispatch/dispatcher.py", line 333, in send
    response = robustapply.robustApply(
  File "/usr/local/lib/python3.8/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/home/kali/Empire/lib/common/empire.py", line 189, in handle_event
    log_event(cur, sender, event_type, json.dumps(signal_data), signal_data['timestamp'], task_id=task_id)
  File "/home/kali/Empire/lib/common/events.py", line 66, in log_event
    cur.execute(
sqlite3.OperationalError: not an error

```

## To Reproduce
...

## Screenshots

![image](https://user-images.githubusercontent.com/5891788/96353541-65f7a280-10cd-11eb-9a2e-d610157f2321.png)
![image](https://user-images.githubusercontent.com/5891788/96353548-6db74700-10cd-11eb-89d5-f975addf289a.png)
![image](https://user-images.githubusercontent.com/5891788/96353552-760f8200-10cd-11eb-961d-e5ba35b855c8.png)

## Additional context

The only solution is to kill the empire process and rerun empire
then it will run but nothing will be display, you have to kill it again
then you can relaunch empire and use it

**Comment by Cx01N** [comment]
I recommend joining the discord and asking questions there since the 3 issues you have opened today appear to be configuration problems.
https://discord.com/invite/P8PZPyf

**Comment by mpgn** [comment]
I don't really see how discord can help to this.
I use latest Kali and i've installed empire using the wiki.

I have 26 agents running at the same time.

**Comment by Cx01N** [comment]
@mpgn I just felt bad that you were having so many problems, I figured it would have been easier to help you out live. But I'm glad you figured it out, I was trying to see if the number of agents was an issue but someone recently got up to 500+ without the database locking up.
