### ISSUE TITLE
Crash when http(s) listener attempts to send agent (stage 2)

### ISSUE THREAD

**Issue by Gloompirate** [BC-SECURITY/Empire#450]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.8.1 BC Security Fork, installed from Kali via apt 

## OS Information (Linux flavor, Python version)
- OS: Kali
- Python: 3.9.2

## Describe the bug
When a stager attempts to contact a http or https listener the listener crashes with the following error:
```
[*] Sending PYTHON stager (stage 1) to 10.200.86.200
[*] Agent 4F70R2YB from 10.200.86.200 posted valid Python PUB key
[*] New agent 4F70R2YB checked in
[+] Initial agent 4F70R2YB from 10.200.86.200 now active (Slack)
[*] Sending agent (stage 2) to 4F70R2YB at 10.200.86.200
[2021-03-31 23:07:24,635] ERROR in app: Exception on /news.php [POST]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/powershell-empire/lib/listeners/http.py", line 1200, in handle_post
    tempListenerOptions['Host']['Value'] = hopListener.options['Host']['Value']
AttributeError: 'NoneType' object has no attribute 'options'
```

## To Reproduce
1: Create http listener
2: Create multi/bash stager
3: Execute stager
4: Listener Crashes

## Expected behavior
Listener should complete stage 2 and send the agent and not crash.

## Screenshots
[https://imgur.com/a/mT8Q0I7](url)

## Additional context
Error as seen from the stager point of view:

```
# Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 23, in <module>
  File "<string>", line 453, in <module>
  File "<string>", line 416, in post_message
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
```

**Comment by Cx01N** [comment]
Can you try running `git update` and reinstalling powershell-empire? It should be on 3.8.2 now which should resolve that issue.

**Comment by Gloompirate** [comment]
Updating to 3.8.2 has resolved this issue.
