### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'pyminifier'

### ISSUE THREAD

**Issue by Tzion0** [BC-SECURITY/Empire#487]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
(Lastest Version)

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20.04.1
- Python: 2.7 / 3.8

## Describe the bug
ModuleNotFoundError: No module named 'pyminifier'

## To Reproduce
Hi, I followed the installation steps in https://bc-security.gitbook.io/empire-wiki/ but i got this error:
```
[*] Installing Poetry
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing pyminifier (2.1): Failed

  EnvCommandError

  Command ['/root/.cache/pypoetry/virtualenvs/empire-bc-security-fork-jINmHm5X-py3.8/bin/pip', 'install', '--no-deps', 'file:///root/.cache/pypoetry/artifacts/8e/51/5f/a46e6ed22dc27d19ee8eca0a25695272c585e35eca2e69420ec77d065a/pyminifier-2.1.tar.gz'] errored with the following return code 1, and output:
  Processing /root/.cache/pypoetry/artifacts/8e/51/5f/a46e6ed22dc27d19ee8eca0a25695272c585e35eca2e69420ec77d065a/pyminifier-2.1.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /root/.cache/pypoetry/virtualenvs/empire-bc-security-fork-jINmHm5X-py3.8/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3e2klfit/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3e2klfit/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-l0dv8hgm
           cwd: /tmp/pip-req-build-3e2klfit/
      Complete output (1 lines):
      error in pyminifier setup command: use_2to3 is invalid.
      ----------------------------------------
  WARNING: Discarding file:///root/.cache/pypoetry/artifacts/8e/51/5f/a46e6ed22dc27d19ee8eca0a25695272c585e35eca2e69420ec77d065a/pyminifier-2.1.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


  at /usr/local/lib/python3.8/dist-packages/poetry/utils/env.py:1180 in _run
      1176│                 output = subprocess.check_output(
      1177│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1178│                 )
      1179│         except CalledProcessError as e:
    → 1180│             raise EnvCommandError(e, input=input_)
      1181│
      1182│         return decode(output)
      1183│
      1184│     def execute(self, bin, *args, **kwargs):


```
While run ```./ps-empire```:
```
$ ./ps-empire server
[*] Loading default config
Traceback (most recent call last):
  File "empire.py", line 11, in <module>
    import empire.server.server as server
  File "/opt/ctf/Empire/empire/server/server.py", line 34, in <module>
    from empire.server.common import empire, helpers
  File "/opt/ctf/Empire/empire/server/common/empire.py", line 34, in <module>
    from . import modules
  File "/opt/ctf/Empire/empire/server/common/modules.py", line 18, in <module>
    from empire.server.common import obfuscation
  File "/opt/ctf/Empire/empire/server/common/obfuscation.py", line 12, in <module>
    from pyminifier import minification as py_minifier
ModuleNotFoundError: No module named 'pyminifier'
```
But i have pyminifier installed on python2.7 and python3.8. What is the cause of this.... ? Thank you in advance for answering this question.

## Expected behavior
Successfully run ./ps-empire

## Screenshots
![image](https://user-images.githubusercontent.com/90162069/134118816-965e7cf0-75e4-4bed-bb24-3547cfe12eba.png)

## Additional context
I wonder did i messed up with my python modules ? I do followed steps in here but not working:
https://github.com/EmpireProject/Empire/issues/1380

**Comment by v3rlly** [comment]
## Temporary solution that worked for me

## Information
* Ubuntu 20.04 (as root)
* Python 3.8.10
* Pip 21.2.4

## To Reproduce

1. Delete `poetry.lock`
2. Edit `pyproject.toml` and remove the line containing `pyminifier = "*"`
3. Run the command `poetry install` (maybe takes some time)
4. Install `pyminifier` manually: `sudo pip3 install pyminifier`
5. Copy the manually installed package to the folder created by Poetry:
```sh
cp -r /usr/local/lib/python3.8/dist-packages/pyminifier /root/.cache/pypoetry/virtualenvs/empire-bc-security-fork-**SOMETHING RANDOM**-py3.8/lib/python3.8/site-packages/
```

Try again: `./ps-empire`

**Comment by Tzion0** [comment]
Hi, thank you, finally, it worked ! Really appreciate what you've done, Thank you so much.

**Comment by Cx01N** [comment]
Thanks for the heads up on this, we removed the package in 4.1.2 which is on the Kali/Sponsor repos, this will hit the public repo sometime this week.
https://github.com/BC-SECURITY/Empire-Sponsors/pull/230
