### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'urllib3' despite module being installed.

### ISSUE THREAD

**Issue by Dave-0-0** [BC-SECURITY/Empire#504]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.x 
- Unknown. It was installed via sudo apt install -y powershell-empire on 10/24/2021. Running with --version results in an error. 

## OS Information (Linux flavor, Python version)
- OS:  Kali Linux 
- Python: 2.7.18
- Python3: 3.9.2

## Describe the bug
Powershell-empire will not run. Gives error about not finding urllib3, despite that module being on the system. 

## To Reproduce
1. Run sudo powershell-empire server
2. Observe error 

## Expected behavior
I expect powershell-empire to start. 

## Additional context
┌──(kali㉿kali)-[/opt/Empire]
└─$ sudo powershell-empire server                                                                                                                                             
Traceback (most recent call last):
  File "/usr/share/powershell-empire/empire.py", line 11, in <module>
    import empire.server.server as server
  File "/usr/share/powershell-empire/empire/server/server.py", line 19, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
┌──(kali㉿kali)-[/opt/Empire]
└─$ pip3 list | grep urllib3
urllib3                      1.26.7
┌──(kali㉿kali)-[/opt/Empire]
└─$ pip list | grep urllib3                                                                                                                                                   
urllib3                      1.26.7
┌──(kali㉿kali)-[/opt/Empire]

**Comment by Cx01N** [comment]
Closing this issue due to inactivity, if it persists please open a new one.
