### ISSUE TITLE
sysinfo

### ISSUE THREAD

**Issue by rossiV1** [BC-SECURITY/Empire#54]
## Empire Version
3.0.1 BC-Security Fork

## OS Information (Linux flavor, Python version)
Ubuntu 18.04, Python 3.6.9

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
when running sysinfo on connected agents, it returned some error.

## Screenshot of error, embedded text output, or Pastebin link to the error

>(Empire: WScy3) > sysinfo
[*] Tasked HWKF93UY to run TASK_SYSINFO
[*] Agent HWKF93UY tasked with task ID 11
(Empire: WScy3) > [!] Error processing result packet from HWKF93UY : a bytes-like object is required, not 'str'

>(Empire: agents) > interact 6S89TUVP
(Empire: 6S89TUVP) > sysinfo
[*] Tasked 6S89TUVP to run TASK_SYSINFO
[*] Agent 6S89TUVP tasked with task ID 1
(Empire: 6S89TUVP) > [!] Error processing result packet from 6S89TUVP : a bytes-like object is required, not 'str'
(Empire: 6S89TUVP) >

**Comment by LaZyDK** [comment]
Copy of #48

**Comment by Hubbl3** [comment]
@rossiV1 I am unable to produce an error with sysinfo are you using a python or powershell agent?

![image](https://user-images.githubusercontent.com/42596432/71699638-28b46500-2d86-11ea-873f-20a635cf31a8.png)

**Comment by rossiV1** [comment]
> @rossiV1 I am unable to produce an error with sysinfo are you using a python or powershell agent?
> 
> ![image](https://user-images.githubusercontent.com/42596432/71699638-28b46500-2d86-11ea-873f-20a635cf31a8.png)

i am using powershell agent. 
for the listener:

> listeners
uselistener http
set Name microsoftupdate
set DefaultJitter 20
set DefaultDelay 6
set DefaultProfile /c/msdownload/update/others/2013/11/9946821_f5082b842c8abc5c47cfc68f98340ec384b69fa9.cab,/c/msdownload/update/software/ftpk/2013/11/ie-spelling-nl_3576e6450352dfc0c0892bf62384e75a56d780a7.msu|Windows-Update-Agent/10.0.10011.16384 Client-Protocol/1.40|Host:download.windowsupdate.com|Accept:*/*
set Headers Content-Type:application/vnd.ms-cab-compressed|Server:Microsoft-IIS/8.5|MSRegion:N. America|Connection:keep-alive|X-Powered-By:ASP.NET

**Comment by Hubbl3** [comment]
@rossiV1 can you also provide me with the command you used to pull down empire?

**Comment by rossiV1** [comment]
I used same command from the github page. when i found error i just use `reset.sh` and install the dependencies.

then i pull using the command from previous issue i posted here https://github.com/BC-SECURITY/Empire/issues/30

> git checkout 3.0-bug-fixes
git pull
./setup/reset.sh

**Comment by rossiV1** [comment]
on the side note, 
the empire server has been online for almost a week, and my previous agents did not manage to connect back and i deleted those stale agents, restarted empire, and i use hta to connect back to empire.

**Comment by Cx01N** [comment]
@rossiV1  We suggest that you redownload the master branch since the official release of 3.0.1 was earlier this week and the 3.0-bug-fixes branch is unstable. I am currently running the most recent release on Ubuntu 19.10 and tried your listener settings, but could not reproduce your issue.

**Comment by rossiV1** [comment]
ok noted. let me try first.

thank you for the fast responses

**Comment by rossiV1** [comment]
i have setup fresh install of empire. and currently had problem of this 

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Empire//lib/listeners/http.py", line 1035, in handle_get
    clientIP)
  File "/opt/Empire/lib/common/agents.py", line 1533, in handle_agent_data
    routingPacket = packets.parse_routing_packet(stagingKey, routingPacket)
  File "/opt/Empire/lib/common/packets.py", line 281, in parse_routing_packet
    sessionID = routingPacket[0:8].decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 0: invalid continuation byte
[2020-01-03 15:46:19,312] ERROR in app: Exception on /c/msdownload/update/others/2013/11/9946821_f5082b842c8abc5c47cfc68f98340ec384b69fa9.cab [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Empire//lib/listeners/http.py", line 1035, in handle_get
    clientIP)
  File "/opt/Empire/lib/common/agents.py", line 1533, in handle_agent_data
    routingPacket = packets.parse_routing_packet(stagingKey, routingPacket)
  File "/opt/Empire/lib/common/packets.py", line 281, in parse_routing_packet
    sessionID = routingPacket[0:8].decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 0: invalid start byte
[2020-01-03 15:46:26,979] ERROR in app: Exception on /c/msdownload/update/software/ftpk/2013/11/ie-spelling-nl_3576e6450352dfc0c0892bf62384e75a56d780a7.msu [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Empire//lib/listeners/http.py", line 1035, in handle_get
    clientIP)
  File "/opt/Empire/lib/common/agents.py", line 1533, in handle_agent_data
    routingPacket = packets.parse_routing_packet(stagingKey, routingPacket)
  File "/opt/Empire/lib/common/packets.py", line 281, in parse_routing_packet
    sessionID = routingPacket[0:8].decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf2 in position 0: invalid continuation byte

I think the previous agents trying to reconnect back to the empire server as i setup listeners at same port

**Comment by rossiV1** [comment]
> @rossiV1 We suggest that you redownload the master branch since the official release of 3.0.1 was earlier this week and the 3.0-bug-fixes branch is unstable. I am currently running the most recent release on Ubuntu 19.10 and tried your listener settings, but could not reproduce your issue.

the sysinfo issue has been resolve. 

only the issue above arise as i use same setup for listener.

**Comment by Cx01N** [comment]
@rossiV1 Im going to close this issue out since sysinfo is working. Can you please open up a new issue for your current agent problem? It will make tracking for us a bit easier. Thanks.
