### ISSUE TITLE
[BUG] Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by Luc1f3r-5705** [BC-SECURITY/Empire#594]
## Empire Version
- 4.7.0 BC Security Fork

## OS Information (Linux flavor, Python version)
- OS: Kali Linux 2022.2
- Python: 3.10.5 & 2.7.18

## Describe the bug
I have installed kali linux freshly on my virtualbox and Powershell-Empire was pre-installed. When I try to run the server this error occurs. I have not configure anything.

**Error:**

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1043, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa95f47ff40>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 786, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='0.0.0.0', port=1337): Max retries exceeded with url: /api/admin/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa95f47ff40>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/powershell-empire/empire.py", line 13, in <module>
    server.run(args)
  File "/usr/share/powershell-empire/empire/server/server.py", line 3374, in run
    server_startup_validator()
  File "/usr/share/powershell-empire/empire/server/server.py", line 3273, in server_startup_validator
    response = requests.post(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='0.0.0.0', port=1337): Max retries exceeded with url: /api/admin/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa95f47ff40>: Failed to establish a new connection: [Errno 111] Connection refused'))

## Expected behavior
The server should connect to local host.

## Screenshots
![image](https://user-images.githubusercontent.com/109689274/180709810-f91a817f-1e46-4297-9ee2-ea19a5be3f84.png)
![image](https://user-images.githubusercontent.com/109689274/180709877-37913490-cbef-4b5e-aeb1-efe25fb711a2.png)

**Comment by Luc1f3r-5705** [comment]
I think the issue was with Virtual Box. I installed into VMWare and works out of the box
