### ISSUE TITLE
[BUG] SyntaxError: invalid decimal literal

### ISSUE THREAD

**Issue by bhavsec** [BC-SECURITY/Empire#630]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.8.3

## OS Information (Linux flavor, Python version)
- OS: Linux kali 5.18.0-kali7-arm64 SMP Debian 5.18.16-1kali1 (2022-08-31) aarch64 GNU/Linux
- Python: Python 3.10.7

## Describe the bug
Not able to run empire server. but client is running successfully.

## To Reproduce

```
┌──(root💀kali)-[~/scripts/Empire]
└─# python3 empire.py server
[*] Loading default config
Traceback (most recent call last):
  File "/root/scripts/Empire/empire.py", line 11, in <module>
    import empire.server.server as server
  File "/root/scripts/Empire/empire/server/server.py", line 35, in <module>
    from empire.server.common import empire, helpers
  File "/root/scripts/Empire/empire/server/common/empire.py", line 36, in <module>
    from . import (
  File "/root/scripts/Empire/empire/server/common/agents.py", line 80, in <module>
    from . import encryption, events, helpers, messages, packets
  File "/root/scripts/Empire/empire/server/common/encryption.py", line 33, in <module>
    from Crypto.Cipher import PKCS1_v1_5
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/PKCS1_v1_5.py", line 73, in <module>
    from Crypto.Util.number import ceil_div
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Util/number.py", line 139
    value |= 2L ** (N-1)                # Ensure high bit is set
             ^
SyntaxError: invalid decimal literal

```

## Screenshots
![Screenshot Parallels Desktop-2022-11-14 at 18 59 43](https://user-images.githubusercontent.com/12765984/201793191-0da2265b-e5f6-400c-9e65-e317a4832531.png)

**Comment by Jackrin** [comment]
You are using an outdated version of pycrypto, Python 3 no longer makes use of trailing L. Therefore the syntax "2L" is wrong, which you can see at the end of the stacktrace. You need to install the newer version of pycrypto: https://pypi.org/project/pycrypto/
