### ISSUE TITLE
[BUG] Sessionmaker error on Kali

### ISSUE THREAD

**Issue by amir-ee** [BC-SECURITY/Empire#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Empire Version

 version (5.4.2-0kali4)

### Python Version

python3

### Operating System

kali linux

### Database

SQLite

### Current Behavior

                                                                                
┌──(amir㉿kali)-[~]
└─$ sudo powershell-empire server     
Traceback (most recent call last):
  File "/usr/share/powershell-empire/empire.py", line 14, in <module>
    import empire.server.server as server
  File "/usr/share/powershell-empire/empire/server/server.py", line 14, in <module>
    from empire.server.api import app
  File "/usr/share/powershell-empire/empire/server/api/app.py", line 15, in <module>
    from empire.server.api.v2.websocket.socketio import setup_socket_events
  File "/usr/share/powershell-empire/empire/server/api/v2/websocket/socketio.py", line 7, in <module>
    from empire.server.api import jwt_auth
  File "/usr/share/powershell-empire/empire/server/api/jwt_auth.py", line 12, in <module>
    from empire.server.api.v2.shared_dependencies import get_db
  File "/usr/share/powershell-empire/empire/server/api/v2/shared_dependencies.py", line 1, in <module>
    from empire.server.core.db.base import SessionLocal
  File "/usr/share/powershell-empire/empire/server/core/db/base.py", line 95, in <module>
    with SessionLocal.begin() as db:
         ^^^^^^^^^^^^^^^^^^
AttributeError: 'sessionmaker' object has no attribute 'begin'
                                                                                
┌──(amir㉿kali)-[~]
└─$ 

### Expected Behavior

why not working

### Steps To Reproduce

                                                                                
┌──(amir㉿kali)-[~]
└─$ sudo powershell-empire server     
Traceback (most recent call last):
  File "/usr/share/powershell-empire/empire.py", line 14, in <module>
    import empire.server.server as server
  File "/usr/share/powershell-empire/empire/server/server.py", line 14, in <module>
    from empire.server.api import app
  File "/usr/share/powershell-empire/empire/server/api/app.py", line 15, in <module>
    from empire.server.api.v2.websocket.socketio import setup_socket_events
  File "/usr/share/powershell-empire/empire/server/api/v2/websocket/socketio.py", line 7, in <module>
    from empire.server.api import jwt_auth
  File "/usr/share/powershell-empire/empire/server/api/jwt_auth.py", line 12, in <module>
    from empire.server.api.v2.shared_dependencies import get_db
  File "/usr/share/powershell-empire/empire/server/api/v2/shared_dependencies.py", line 1, in <module>
    from empire.server.core.db.base import SessionLocal
  File "/usr/share/powershell-empire/empire/server/core/db/base.py", line 95, in <module>
    with SessionLocal.begin() as db:
         ^^^^^^^^^^^^^^^^^^
AttributeError: 'sessionmaker' object has no attribute 'begin'
                                                                                
┌──(amir㉿kali)-[~]

**Comment by Cx01N** [comment]
I recommend installing the Github version, it seems the Kali version is a few versions behind. That should hopefully resolve the issue.

**Comment by vinnybod** [comment]
Agreed, looks like you have the wrong version of SQLAlchemy installed.
