### ISSUE TITLE
[BUG] Empire after installation error

### ISSUE THREAD

**Issue by ARJUN0601** [BC-SECURITY/Empire#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Empire Version

5.10.2

### Python Version

Python 3.11.2

### Operating System

Parrot OS

### Database

MySQL

### Current Behavior

┌─[root@parrot]─[/home/drevello/Desktop/tools/Empire]
└──╼ #./ps-empire server
Traceback (most recent call last):
  File "/home/drevello/Desktop/tools/Empire/empire.py", line 11, in <module>
    import empire.server.server as server
  File "/home/drevello/Desktop/tools/Empire/empire/server/server.py", line 13, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
┌─[✗]─[root@parrot]─[/home/drevello/Desktop/tools/Empire]
└──╼ #

### Expected Behavior

i expected it shouldnt show any error and run smoothly

### Steps To Reproduce

1.Install Parrot Os update it by adding kali linux repo in sources.list.d along with key
2.git clone --recursive https://github.com/BC-SECURITY/Empire.git
3.cd Empire
4. ./setup/checkout-latest-tag.sh
5. ./ps-empire install -y

### Anything else?

this always happened in every version of empire

**Comment by vinnybod** [comment]
Closing as an environment/incomplete-install issue. `urllib3` is a declared dependency (`urllib3 = "^2.6.3"` in `pyproject.toml`), so a proper `poetry install` run under the Poetry venv provides it — a `ModuleNotFoundError: urllib3` means the server was launched outside the environment where dependencies were installed. If you hit a missing-module error on a current release after a clean install, please open a fresh issue with your exact install steps.

*This comment was written by Claude with my guidance and reviewed by me before posting.*
