### ISSUE TITLE
[BUG] Failed installation

### ISSUE THREAD

**Issue by phasm1d** [BC-SECURITY/Empire#758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Empire Version

5.11.5

### Python Version

3.12.0

### Operating System

Kali linux 2024-09-26

### Database

SQLite

### Current Behavior

Installation fails when install python modules through poetry with the following error:
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/home/kali/.local/share/pypoetry/venv/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/usr/lib/python3.11'
  sys._base_executable = '/usr/bin/python'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.platlibdir = 'lib'
  sys.executable = '/home/kali/.local/share/pypoetry/venv/bin/python'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f9e09c69080 (most recent call first):
  <no Python frame>

Then using ps-empire binary always shows that error.

### Expected Behavior

Empire should normally install

### Steps To Reproduce

Just download latest Kali linux release and follow installation steps from documentation.

**Comment by githbubble** [comment]
same on kali

**Comment by kirtcathey** [comment]
Still same issue coming up when following the installation instructions... everywhere. Seems to randomly show different modules not found errors. The latest one shows yaml not found and know that I have yaml installed. Same error on Kali and Parrot... at least some consistency there.

**Comment by Cx01N** [comment]
We pushed out a few fixes. Are you still having the same issue?

**Comment by sh6ll** [comment]
it still doesn't work. 

(venv) kali@ubuntu:~/Empire$ sudo ./ps-empire server
Creating virtualenv empire-bc-security-fork-aTjsf76n-py3.10 in /root/.cache/pypoetry/virtualenvs
Traceback (most recent call last):
  File "/home/kali/Empire/empire.py", line 5, in <module>
    from empire import arguments, config_manager
  File "/home/kali/Empire/empire/config_manager.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
(venv) kali@ubuntu:~/Empire$ pip3 install pyyaml
Requirement already satisfied: pyyaml in ./venv/lib/python3.10/site-packages (6.0.2)
(venv) kali@ubuntu:~/Empire$ sudo ./ps-empire server
Traceback (most recent call last):
  File "/home/kali/Empire/empire.py", line 5, in <module>
    from empire import arguments, config_manager
  File "/home/kali/Empire/empire/config_manager.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by vinnybod** [comment]
The latest Empire version (6) has been tested on kali with the install script and it works. Please try again and re-open this issue if the problem persists.
