### ISSUE TITLE
[BUG] <title> Powershell empire python module issue

### ISSUE THREAD

**Issue by ARJUN0601** [BC-SECURITY/Empire#762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Empire Version

5.11.7

### Python Version

pip 23.0.1 from /root/.cache/pypoetry/virtualenvs/empire-bc-security-fork-Eci4yFVd-py3.11/lib/python3.11/site-packages/pip (python 3.11)

### Operating System

Parrot Security OS 6.2

### Database

MySQL

### Current Behavior

i was installing powershell empire from source.
but i am getting error about python-virtualenv module error
its hard to explain then showing error output

┌─[root@parrot]─[/home/drevello]
└──╼ #powershell-empire server
Traceback (most recent call last):
  File "/usr/share/powershell-empire/empire.py", line 11, in <module>
    from empire.server import server
  File "/usr/share/powershell-empire/empire/server/server.py", line 15, in <module>
    from empire.server.common import empire
  File "/usr/share/powershell-empire/empire/server/common/empire.py", line 20, in <module>
    from empire.server.core.agent_service import AgentService
  File "/usr/share/powershell-empire/empire/server/core/agent_service.py", line 12, in <module>
    from empire.server.core.agent_task_service import AgentTaskService
  File "/usr/share/powershell-empire/empire/server/core/agent_task_service.py", line 23, in <module>
    from empire.server.core.listener_service import ListenerService
  File "/usr/share/powershell-empire/empire/server/core/listener_service.py", line 9, in <module>
    from empire.server.core.db.base import SessionLocal
  File "/usr/share/powershell-empire/empire/server/core/db/base.py", line 12, in <module>
    from empire.server.core.db.defaults import (
  File "/usr/share/powershell-empire/empire/server/core/db/defaults.py", line 7, in <module>
    from passlib import pwd
  File "/root/.cache/pypoetry/virtualenvs/empire-bc-security-fork-Eci4yFVd-py3.11/lib/python3.11/site-packages/passlib/pwd.py", line 16, in <module>
    import pkg_resources
  File "/root/.cache/pypoetry/virtualenvs/empire-bc-security-fork-Eci4yFVd-py3.11/lib/python3.11/site-packages/pkg_resources.py", line 29, in <module>
    import symbol
ModuleNotFoundError: No module named 'symbol'
┌─[✗]─[root@parrot]─[/home/drevello]
└──╼ #

### Expected Behavior

i expected to work very well

### Steps To Reproduce

cd /usr/share/powershell-empire
#. empire/bin/activate
. ~/.cache/pypoetry/virtualenvs/empire-bc-security-fork-Eci4yFVd-py3.11/bin/activate
exec python3 empire.py "$@"

### Anything else?

and project missing requirements.txt for installing required module for using powershell-empire after from source
i have to install it from error manually one by one

**Comment by kirtcathey** [comment]
I am getting the same thing all the way through, except module 'jq' in both Parrot OS 2 and the latest Kali (both fresh installs) and I know jq is installed.

**Comment by ARJUN0601** [comment]
> I am getting the same thing all the way through, except module 'jq' in both Parrot OS 2 and the latest Kali (both fresh installs) and I know jq is installed.

I even tried installing through source but it having error saying symbol module is not found
Now I am using it in docker container

**Comment by Cx01N** [comment]
Are you still seeing this issue? I've had it pop up occasionally but usually `apt update` tends to resolve it.

**Comment by kirtcathey** [comment]
> Are you still seeing this issue? I've had it pop up occasionally but usually `apt update` tends to resolve it.

Yes, and it's too bad. I want to use the solution, but every time I have tried to use it (for about five years now) some error or another pops up. This time I was determined to use the product and went through the trouble of doing fresh installs of Parrot, Kali, and Debian.... all come up with the same error: 
/usr/lib/python3/dist-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.3.0) or chardet (5.1.0)/charset_normalizer (3.0.1) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "/usr/share/powershell-empire/empire.py", line 11, in <module>
    import empire.server.server as server
  File "/usr/share/powershell-empire/empire/server/server.py", line 14, in <module>
    from empire.server.common import empire
  File "/usr/share/powershell-empire/empire/server/common/empire.py", line 18, in <module>
    from empire.server.core import hooks_internal
  File "/usr/share/powershell-empire/empire/server/core/hooks_internal.py", line 5, in <module>
    import jq as jq
ModuleNotFoundError: No module named 'jq'

**Comment by vinnybod** [comment]
@ARJUN0601 The steps to reproduce don't seem like instructions that we recommend.
```
cd /usr/share/powershell-empire
#. empire/bin/activate
. ~/.cache/pypoetry/virtualenvs/empire-bc-security-fork-Eci4yFVd-py3.11/bin/activate
exec python3 empire.py "$@"
```

Have you tried following the quickstart in the readme? https://github.com/BC-SECURITY/Empire?tab=readme-ov-file#quickstart

**Comment by kirtcathey** [comment]
I have read the quickstart and various getting started tutorials many times. In the Parrot and Kali default install there is no empire/bin/ folder, much less some activate binary.

In the quickstart, I go to start the server then get some other module not installed error for a module that I very well know is installed.

**Comment by kirtcathey** [comment]
Did it one more time per the quickstart and get this... on installation.
./ps-empire install -y 
ヒット:1 https://packages.microsoft.com/debian/12/prod bookworm InRelease
ヒット:2 https://deb.parrot.sh/parrot lory InRelease
ヒット:3 https://deb.parrot.sh/direct/parrot lory-security InRelease
ヒット:4 https://deb.parrot.sh/parrot lory-backports InRelease
ヒット:5 https://repo.protonvpn.com/debian stable InRelease   
パッケージリストを読み込んでいます... 完了
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています... 完了        
状態情報を読み取っています... 完了        
wget はすでに最新バージョン (1.21.3-1+b2) です。
git はすでに最新バージョン (1:2.39.5-0+deb12u1) です。

---- snip ----


libpango-1.0-0 はすでに最新バージョン (1.50.12+ds-1) です。
libharfbuzz0b はすでに最新バージョン (6.0.0+dfsg-3) です。
libpangoft2-1.0-0 はすでに最新バージョン (1.50.12+ds-1) です。
以下のパッケージが自動でインストールされましたが、もう必要とされていません:
  ldap-utils libc++1-19 libc++abi1-19 libdaxctl1 libndctl6 libpmem1 libunwind-19 linux-compiler-gcc-12-x86
  linux-headers-6.5.0-13parrot1-common linux-kbuild-6.5.0-13parrot1 python3-pcapy samba upx-ucl
これを削除するには 'sudo apt autoremove' を利用してください。
アップグレード: 0 個、新規インストール: 0 個、削除: 0 個、保留: 101 個。
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています... 完了        
状態情報を読み取っています... 完了        
curl はすでに最新バージョン (8.11.1-1~bpo12+1) です。
git はすでに最新バージョン (1:2.39.5-0+deb12u1) です。
gcc はすでに最新バージョン (4:12.2.0-3) です。
gcc は手動でインストールしたと設定されました。
xz-utils はすでに最新バージョン (5.4.1-0.2) です。
インストールすることができないパッケージがありました。おそらく、あり得
ない状況を要求したか、(不安定版ディストリビューションを使用しているの
であれば) 必要なパッケージがまだ作成されていなかったり Incoming から移
動されていないことが考えられます。
以下の情報がこの問題を解決するために役立つかもしれません:

以下のパッケージには満たせない依存関係があります:
 libcurl4-gnutls-dev : 依存: libcurl3-gnutls (= 7.88.1-10+deb12u8) しかし、8.11.1-1~bpo12+1 はインストールされようとしています
E: 問題を解決することができません。壊れた変更禁止パッケージがあります。
/usr/lib/python3/dist-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.3.0) or chardet (5.1.0)/charset_normalizer (3.0.1) doesn't match a supported version!
  warnings.warn(
usage: empire.py [-h] {server,client,sync-starkiller,install} ...

positional arguments:
  {server,client,sync-starkiller,install}
    server              Launch Empire Server
    client              Launch Empire CLI
    sync-starkiller     Sync Starkiller submodule with the config
    install             Install the Empire framework

options:
  -h, --help            show this help message and exit
Traceback (most recent call last):
  File "/usr/share/Empire/empire.py", line 5, in <module>
    from empire import arguments, config_manager
  File "/usr/share/Empire/empire/config_manager.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by kirtcathey** [comment]
Same thing happens in Kali...

**Comment by vinnybod** [comment]
The latest Empire version (6) has been tested on kali with the install script and it works. Please try again and re-open this issue if the problem persists.
